version: '3.8'
networks:
    asrdb-network:

services:
    asrdb-gateway:
        networks:
            - asrdb-network
        image: ghrc.io/florianika/asrdb-gateway:latest
        ports:
            - "80:80"
        hostname: asrdb-gateway
    #asrdb-auth:
    #    networks:
    #        - asrdb-network
    #    image: ghrc.io/florianika/asrdb-auth:latest
    #    hostname: asrdb-auth
    #asrdb-mssql:
    #    networks:
    #        - asrdb-network
    #    image: mcr.microsoft.com/mssql/server:2022-latest
    #    ports:
    #        - "1433:1433"
    #    environment:
    #        - ACCEPT_EULA=Y
    #        - MSSQL_SA_PASSWORD=123456
    #        - MSSQL_PID=Developer
    #    hostname: asrdb-mssql
    ardb-arcgis-python:
        networks:
            - asrdb-network
        image: ghrc.io/florianika/asrdb-arcgis-python:latest
        ports:
            - "8888:8888"
        hostname: asrdb-arcgis-python

