version: '3.8'
networks:
    asrbd-network:

services:
    asrbd-gateway:
        networks:
            - asrbd-network
        image: ghcr.io/florianika/asrbd-gateway:latest
        ports:
            - "9090:8080"
        hostname: asrbd-gateway
    asrbd-auth:
        networks:
            - asrbd-network
        image: ghcr.io/florianika/asrbd-auth:latest
        ports:
            - "8080:8080"
        hostname: asrbd-auth
#    asrdb-mssql:
#        networks:
#            - asrdb-network
#        image: mcr.microsoft.com/mssql/server:2022-latest
#        ports:
#            - "1433:1433"
#        environment:
#            - ACCEPT_EULA=Y
#            - MSSQL_SA_PASSWORD=RjttMBnnbgjptw4G
#            - MSSQL_PID=Developer
#        volumes:
#            -  sqlservervolume:/var/opt/mssql
#        hostname: asrdb-mssql
    #asrdb-arcgis-python:
    #   networks:
    #        - asrdb-network
    #    image: ghcr.io/florianika/asrdb-arcgis-python:latest
    #    ports:
    #        - "8888:8888"
    #    hostname: asrdb-arcgis-python
    asrbd-qms:
        networks:
            - asrbd-network
        image: ghcr.io/florianika/asrbd-qms:latest
        ports:
            - "8088:8080"
        hostname: asrbd-qms
#    asrdb-frontend:
#        image: ghcr.io/florianika/asrdb-frontend:latest
#        ports:
#            - "80:80"

#volumes:
#    sqlservervolume: test