version: '3.8'
networks:
    asrdb-network:

services:
    asrdb-gateway:
        networks:
            - asrdb-network
        image: ghcr.io/florianika/asrdb-gateway:latest
        ports:
            - "9090:80"
        hostname: asrdb-gateway
    asrdb-auth:
        networks:
            - asrdb-network
        image: ghcr.io/florianika/asrdb-auth:latest
        ports:
            - "8080:80"
        hostname: asrdb-auth
    asrdb-mssql:
        networks:
            - asrdb-network
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=RjttMBnnbgjptw4G
            - MSSQL_PID=Developer
        volumes:
            -  sqlservervolume:/var/opt/mssql
        hostname: asrdb-mssql
    asrdb-arcgis-python:
        networks:
            - asrdb-network
        image: ghcr.io/florianika/asrdb-arcgis-python:latest
        ports:
            - "8888:8888"
        hostname: asrdb-arcgis-python
    asrdb-qms:
        networks:
            - asrdb-network
        image: ghcr.io/florianika/asrdb-qms:latest
        ports:
            - "8088:80"
        hostname: asrdb-qms
    asrdb-frontend:
        image: ghcr.io/florianika/asrdb-frontend:latest
        ports:
            - "80:80"

volumes:
    sqlservervolume: