using System;

namespace Domain.Enum
{
    public enum BuildingClass
    {
        ONE_DWELLING_BUILDING = 111,
        TWO_DWELLING_BUILDING = 112,
        THREE_OR_MORE_DWELLING_BUILDING = 115,
        RESIDENCE_FOR_COMMUNITIES = 117,
        HOTELS_AND_SIMILAR_BUILDING = 121,
        OFFICE_BUILDING = 122,
        WHOLESALE_AND_RETAIL_TRADE_BUILDING = 123,
        TRAFFIC_AND_COMMUNICATION_BUILDING = 124,
        INDUSTRIAL_OR_WAREHOUSE_BUILDING = 125,
        PUBLIC_ENTERTAIMENT_EDU_HEALTH_INSTITUTIONAL_BUILDING = 126,
        OTHER_NON_RESIDENTIAL_BUILDING = 127,
        BUILDING_CLASS_NOT_APPLICABLE = 900,
        UNKNOWN_BUILDING_CLASS = 999
    }
}
